### ISSUE TITLE
Is there a way to save all the failed test cases in some text file or in a list?

### ISSUE THREAD

**Issue by nishnk-vishi** [marcotcr/checklist#125]
We need to save the all the failed test cases in a text file. Is there a way to save them??

**Comment by marcotcr** [comment]
Do you only want the failed ones? If you want all tests, there is `test.to_raw_file('/tmp/raw_file.txt')` (see lines 16-21 of [this](https://github.com/marcotcr/checklist/blob/master/notebooks/tutorials/3.%20Test%20types,%20expectation%20functions,%20running%20tests.ipynb)).

If you only want the failed ones, you can do the same thing (but you need to call `test.to_raw_file` before running it, because that messes up the index), and get the index of failed testcases from `test.results.passed` (where `True` means it passed the test, so you just filter by `False`)
