### ISSUE TITLE
Labelled data

### ISSUE THREAD

**Issue by burakisikli** [marcotcr/checklist#42]
Hi,
First of all, thank you for sharing your work.
How can I get labelled data(text, ground truth) to calculate uncertainty in these tasks?  I couldn't see any function about it. In the tests_n500 file, there are only sample texts without any label.

Thanks for advance
Best

**Comment by marcotcr** [comment]
Tests often have expectations that go beyond 'the prediction must equal this ground truth'.
For example, let's say you run the following, to load the sentiment suite:
```python
import checklist
from checklist.test_suite import TestSuite
suite_path = '../release_data/sentiment/sentiment_suite.pkl'
suite = TestSuite.from_file(suite_path)
```

Simple MFTs may have labels, e.g.:

```python
print(suite.tests['Sentiment-laden words in context'].data[:5])
print(suite.tests['Sentiment-laden words in context'].labels[:5])
```
> ['The flight is good.', 'This flight is good.', 'That flight is good.', 'The flight was good.', 'This flight was good.']
[2, 2, 2, 2, 2]

In this case `0` is negative, `1` is neutral, `2` is positive.
Other tests, like `suite.tests['add random urls and handles']`, will not have `labels`, because the expectation is encoded in the expectation function (in this case, the expectation is 'prediction should not change, with a margin of tolerance')
